### ISSUE TITLE
max_pool_buffers PV in areadetector

### ISSUE THREAD

**Issue by bruceravel** [bluesky/ophyd#1007]
@jwlodek pointed this out: https://github.com/areaDetector/ADCore/commit/47c70bf10644c63955c00646eaffd881f8a1a9bc#diff-81f46c90905195f7c7370bb9f6e8a240eeb448f9b7ec0cc0034a72ae8fab639e

It seems that the areaDetetcor IOC no longer provides a MaxPoolBuffers PV.  I am seeing this as a problem when trying to implement a new camera at BMM.  The CSS screen works, but I also need to interact with the camera in bluesky.  The ophyd 
object derived from AreaDetector 

```python
class CAMERA(SingleTrigger, AreaDetector):
    image = Cpt(ImagePlugin, 'image1:')
usb1 = CAMERA('XF:06BM-ES{UVC-Cam:1}', name='usb1')
```

fails with 

```
BMM E.111 [3] ▶ usb1.image.get()
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2021-1.2/lib/python3.7/site-packages/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'pool_max_buffers'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<ipython-input-3-3af59cac6da0>", line 1, in <module>
    usb1.image.get()
  File "/opt/conda_envs/collection-2021-1.2/lib/python3.7/site-packages/ophyd/device.py", line 1360, in get
    signal = getattr(self, attr)
  File "/opt/conda_envs/collection-2021-1.2/lib/python3.7/site-packages/ophyd/device.py", line 225, in __get__
    return instance._instantiate_component(self.attr)
  File "/opt/conda_envs/collection-2021-1.2/lib/python3.7/site-packages/ophyd/device.py", line 1218, in _instantiate_component
    self._signals[attr] = cpt.create_component(self)
  File "/opt/conda_envs/collection-2021-1.2/lib/python3.7/site-packages/ophyd/device.py", line 182, in create_component
    cpt_inst.wait_for_connection()
  File "/opt/conda_envs/collection-2021-1.2/lib/python3.7/site-packages/ophyd/signal.py", line 1069, in wait_for_connection
    self._ensure_connected(self._read_pv, timeout=timeout)
  File "/opt/conda_envs/collection-2021-1.2/lib/python3.7/site-packages/ophyd/signal.py", line 1046, in _ensure_connected
    raise TimeoutError(f"{pv.pvname} could not connect within "
TimeoutError: XF:06BM-ES{UVC-Cam:1}image1:PoolMaxBuffers could not connect within 1.0-second timeout.
```

**Comment by mrakitin** [comment]
@bruceravel, did it work? If so, please close this issue.

**Comment by bruceravel** [comment]
Yes, using V33 resolved this problem.  Thanks for the help @mrakitin!
